POST http://localhost:3005/api/producto
Content-Type: application/json

{
  "name": "Televisor Smart",
  "category": "Electrónicos",
  "price": "1200",
  "stock": "50",
  "description": "Televisor inteligente de última generación",
  "color": "Negro",
  "dimensions": {
    "height": "70",
    "width": "120",
    "depth": "10"
  },
  "imageUrl": "https://example.com/tv.jpg",
  "tipo_producto_id": "673cd2c95791df6971663a20"
}


### Obtener todos los productos
GET http://localhost:3005/api/producto

### Obtener un producto por ID
GET http://localhost:3005/api/producto/67f4104eb103f29cb5d0a2bc

### Actualizar un producto por ID
PUT http://localhost:3005/api/producto/67f4104eb103f29cb5d0a2bc
Content-Type: application/json

{
  "name": "Televisor OLED",
  "category": "Electrónicos",
  "price": "5000",
  "stock": "40",
  "description": "Televisor OLED con resolución 4K",
  "color": "Gris",
  "dimensions": {
    "height": "80",
    "width": "130",
    "depth": "12"
  },
  "imageUrl": "https://example.com/oled-tv.jpg",
  "tipo_producto_id": "673cd2c95791df6971663a20"
}

### Eliminar un producto por ID
DELETE http://localhost:3005/api/producto/67f4104eb103f29cb5d0a2bc

