###
POST http://localhost:3005/api/inventario HTTP/1.1
Content-Type: application/json

{
    "cantidad": "100 unidades",
    "id_producto": "645cd12c3f791aa71b567c20",
    "id_material": "645cd22d5a791aa71b567d34"
}

###
GET http://localhost:3005/api/inventario HTTP/1.1

###
GET http://localhost:3005/api/inventario/645cd12c3f791aa71b567c20 HTTP/1.1

###
DELETE http://localhost:3005/api/inventario/645cd12c3f791aa71b567c20 HTTP/1.1
