### Crear un nuevo producto
POST http://localhost:3005/api/producto

{
  "name": "Televisor Smart",
  "category": "Electrónicos",
  "price": "1200",
  "stock": "50",
  "description": "Televisor inteligente de última generación",
  "color": "Negro",
  "dimensions": {
    "height": "70",
    "width": "120",
    "depth": "10"
  },
  "imageUrl": "https://example.com/tv.jpg",
  "tipo_producto_id": "673cd2c95791df6971663a20"
}

### Obtener todos los productos
GET http://localhost:3005/api/producto

### Obtener un producto por ID
GET http://localhost:3005/api/producto/674609109e416253c5049b21

### Actualizar un producto por ID
PUT http://localhost:3005/api/producto/674609109e416253c5049b21

{
  "name": "Televisor OLED",
  "category": "Electrónicos",
  "price": "1500",
  "stock": "40",
  "description": "Televisor OLED con resolución 4K",
  "color": "Gris",
  "dimensions": {
    "height": "80",
    "width": "130",
    "depth": "12"
  },
  "imageUrl": "https://example.com/oled-tv.jpg",
  "tipo_producto_id": "673cd2c95791df6971663a20"
}

### Eliminar un producto por ID
DELETE http://localhost:3005/api/producto/674609109e416253c5049b21

{
  "nombre": "Televisor OLED",
  "precio": 1500,
  "descripcion": "Televisor OLED con resolución 4K",
  "tipo_producto_id": "673cd2c95791df6971663a20"
}
###
DELETE http://localhost:3005/api/producto/674609109e416253c5049b21 HTTP/1.1
