###  

POST http://localhost:3000/api/estado HTTP/1.1
Content-Type: application/json

{
    "estado" : "Activo"
}

###
GET http://localhost:3000/api/estado HTTP/1.1 
#metodo para mostrar todos los datos existentes en la base de datos

###
GET http://localhost:3000/api/estado/6737d0b2e5a56c9c1570e365 HTTP/1.1
#Metodo para mostrar los datos de un id especifico

###
PUT http://localhost:3000/api/estado/6737d0b2e5a56c9c1570e365 HTTP/1.1
Content-Type: application/json
#Metodo para actualizar los datos de un id en especifico
{
    "estado" : "Inactivo"
}

###
DELETE http://localhost:3000/api/estado/6737d0b2e5a56c9c1570e365 HTTP/1.1
#Metodo para borrar los datos de un id en especifico