###
POST http://localhost:3005/api/usuario HTTP/1.1
content-Type: application/json

{    
    "nombres":"Santiago Sneither",
    "apellidos":"Pabon Barrera",
    "correo":"sntiago25@gmail.com",
    "num_doc": "1022365221",
    "contraseña":"santi201"
}

###
GET http://localhost:3005/api/usuario HTTP/1.1

### 
GET http://localhost:3005/api/usuario/673cd2c95791df6971663a20 HTTP/1.1

###
PUT http://localhost:3005/api/usuario/673cd2c95791df6971663a20 HTTP/1.1
Content-Type: application/json

{    
    "nombres":"Santiago Sneither",
    "apellidos":"Pabon Barrera",
    "correo":"sntia2005@gmail.com",
    "num_doc": "1022365221",
    "contraseña":"elloco5699"
}

###
DELETE http://localhost:3005/api/usuario/6737ca6a715cd2aa1ad757ed HTTP/1.1

